package com.huangpf.po;

public class UserT {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_T.ID
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_T.USER_NAME
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_T.PASSWORD
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_T.AGE
     *
     * @mbggenerated
     */
    private Short age;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_T
     *
     * @mbggenerated
     */
    public UserT(Long id, String userName, String password, Short age) {
        this.id = id;
        this.userName = userName;
        this.password = password;
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_T.ID
     *
     * @return the value of USER_T.ID
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_T.USER_NAME
     *
     * @return the value of USER_T.USER_NAME
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_T.PASSWORD
     *
     * @return the value of USER_T.PASSWORD
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_T.AGE
     *
     * @return the value of USER_T.AGE
     *
     * @mbggenerated
     */
    public Short getAge() {
        return age;
    }
}